# Generated by Django 5.0.2 on 2025-09-30 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom quantity value (e.g., 250, 1.5)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_unit',
            field=models.CharField(blank=True, choices=[('ml', 'Milliliter'), ('l', 'Liter'), ('g', 'Gram'), ('kg', 'Kilogram'), ('nos', 'Numbers'), ('pcs', 'Pieces')], help_text="Custom unit for the quantity (e.g., 'g', 'kg', 'ml')", max_length=10, null=True),
        ),
    ]
