# Generated by Django 5.0.2 on 2025-08-30 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Offer price of the product (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Original price of the product (default: 10000 Rs)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
