# Generated by Django 5.0.2 on 2025-09-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='1 kg', help_text="Product unit (e.g., '1 kg', '500 ml', '10 nos')", max_length=50),
        ),
    ]
