# Generated by Django 5.0.2 on 2025-09-24 05:49

from django.db import migrations, models


def update_original_price(apps, schema_editor):
    """Update existing products to set original_price to price value"""
    Product = apps.get_model('products', 'Product')
    
    # Update all products where original_price is None or 10000 (old default)
    products_to_update = Product.objects.filter(
        models.Q(original_price__isnull=True) | 
        models.Q(original_price=10000.00)
    )
    
    for product in products_to_update:
        product.original_price = product.price
        product.save(update_fields=['original_price'])


def reverse_update_original_price(apps, schema_editor):
    """Reverse migration - set original_price back to 10000 for products where it equals price"""
    Product = apps.get_model('products', 'Product')
    
    # Set original_price to 10000 for products where original_price equals price
    products_to_reverse = Product.objects.filter(original_price=models.F('price'))
    
    for product in products_to_reverse:
        product.original_price = 10000.00
        product.save(update_fields=['original_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_update_original_price_default'),
    ]

    operations = [
        migrations.RunPython(update_original_price, reverse_update_original_price),
    ]
