# Generated by Django 5.0.2 on 2025-09-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('solid', 'Solid (Rice, Pulses, etc.)'), ('liquid', 'Liquid (Oil, etc.)'), ('other', 'Other')], default='solid', help_text='Product type determines available quantity variants', max_length=10),
        ),
    ]
