# Generated by Django 5.0.2 on 2025-10-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_in_stock',
            field=models.BooleanField(default=True, help_text='Manually mark product as in stock or out of stock'),
        ),
    ]
